places = ["Norway", "Dalhousie", "Canada", "Himalya", "Gurdaspur"]
print(places)
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
